WL-3819: Email not sent if user tries to visit non-existant site
ox-it/sakai pull request #222
Opened 2016-09-23 15:08 UTC by nicholaswilson100

and then uses contact us tool to report a problem with content.

2016-09-23 15:08 UTC, nicholaswilson100 commented
Line 186, this ' request.getParameter("siteId")' wasn't doing anything, i.e., equals null.

2016-09-26 09:15 UTC, buckett commented on feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java
> +            siteId = request.getContextPath().split("/portal")[1];
Array access without check based on something that comes from the request looks like a NullPointerException waiting to happen.

2016-09-26 09:15 UTC, buckett requested changes

2016-10-03 14:26 UTC, nicholaswilson100 commented on feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java
> +            siteId = request.getContextPath().split("/portal")[1];
Fixed

2016-10-03 14:27 UTC, nicholaswilson100 commented
It turns out it's not really necessary to process the request's contextPath ; we can just pass the whole thing through.

2016-10-03 15:47 UTC, buckett commented on feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java
> +            return request.getContextPath();
This then means that the contact address for the site the user was trying to access doesn't work.

2016-10-03 16:46 UTC, merged