WL-4922 Add option to display nodes in the hierarchy of a site in ent…
ox-it/sakai pull request #405
Opened 2017-06-06 11:26 UTC by RebeccaOxfordUni

…ity broker.

2017-06-07 09:21 UTC, buckett requested changes

2017-06-07 09:21 UTC, buckett commented on tetraelf-hierarchy/hierarchy-api/api/src/java/org/sakaiproject/hierarchy/api/PortalHierarchyService.java
> +	/**
Why duplicate a SiteService method in the PortalHierarchyService?

2017-06-07 09:21 UTC, buckett commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +			throw new IllegalArgumentException("No site found for the given site ID");
Shouldn't the message be that the site ID doesn't exist?

2017-06-07 09:21 UTC, buckett commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +				throw new IllegalArgumentException("You do not have permission to view any pages that include this site");
It seems strange to throw an error if you can't see all the nodes, but if you can see one return that one and don't tell the user there might be hidden ones.

2017-06-07 09:21 UTC, buckett commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +					if ((pn.getId()).equals(portalNodePrimary.getId())) {
How about `pn.equals(portalNodePrimary)`?
The equals is `null` safe in the case there isn't a default node (unlikely). When reading code I'm wondering what's the reason for not using the plain `equals()`, eg, what edge case is this trying to catch.

2017-06-07 09:21 UTC, buckett commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/PortalNodeSummary.java
> +	public void setPrimary(boolean primary){
Why have the setter if you've already go the `@Data` annotation?

2017-06-08 08:20 UTC, RebeccaOxfordUni commented on tetraelf-hierarchy/hierarchy-api/api/src/java/org/sakaiproject/hierarchy/api/PortalHierarchyService.java
> +	/**
Because there is a PortalHierarchyService object in HierarchyEntityProviderImpl but not a SiteService object.

2017-06-08 08:20 UTC, RebeccaOxfordUni commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +					if ((pn.getId()).equals(portalNodePrimary.getId())) {
Ok, will change it to equals

2017-06-08 08:21 UTC, buckett commented on tetraelf-hierarchy/hierarchy-api/api/src/java/org/sakaiproject/hierarchy/api/PortalHierarchyService.java
> +	/**
But why not add it?

2017-06-08 08:24 UTC, buckett commented on tetraelf-hierarchy/hierarchy-api/api/src/java/org/sakaiproject/hierarchy/api/PortalHierarchyService.java
> +	/**
The API is supposed to be the services that you expose to the reset of Sakai, it's your contract to other tools/services wanting to use your functionality. Having a proxy method as part of that API leads to the API being larger and so harder to understand. Also someone reading the code who has seen `SiteService.siteExists()` can understand it somewhere else, however if I see `PortalHierarchService.siteExists()` I need to read JavaDoc/source to check what it actually does.

2017-06-08 08:24 UTC, RebeccaOxfordUni commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +				throw new IllegalArgumentException("You do not have permission to view any pages that include this site");
I'll find out the requirements in these situations.

2017-06-08 08:24 UTC, RebeccaOxfordUni commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +			throw new IllegalArgumentException("No site found for the given site ID");
Ok, I'll change it.

2017-06-08 08:51 UTC, RebeccaOxfordUni commented on tetraelf-hierarchy/hierarchy-api/api/src/java/org/sakaiproject/hierarchy/api/PortalHierarchyService.java
> +	/**
Ok, will add SiteService.

2017-06-08 09:23 UTC, RebeccaOxfordUni commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +				throw new IllegalArgumentException("You do not have permission to view any pages that include this site");
It looks to me as if this check isn't necessary, if one can see a site one seems to be able to see it anywhere in the hierarchy, even if one doesn't have access to the parent site, is this what you think is the case Matthew?

2017-06-08 10:20 UTC, buckett commented on tetraelf-hierarchy/hierarchy-tool/tool/src/java/org/sakaiproject/hierarchy/tool/entityproviders/HierarchyEntityProviderImpl.java
> +				throw new IllegalArgumentException("You do not have permission to view any pages that include this site");
Yep, seems good.

2017-06-09 12:36 UTC, RebeccaOxfordUni commented
Changes made Matthew, can you check again pls?

2017-06-09 13:36 UTC, buckett approved these changes
Yeah looks good.

2017-06-09 13:36 UTC, merged