WL-5103 Validate survey's email template before saving.
ox-it/sakai pull request #491
Opened 2018-04-19 12:03 UTC by RebeccaOxfordUni

![capture](https://user-images.githubusercontent.com/17832659/38990412-b2f9cfb4-43c9-11e8-8814-028241d861eb.JPG)

2018-04-20 08:30 UTC, buckett requested changes
Look good, just the imports I think.

2018-04-20 08:30 UTC, buckett commented on evaluations/impl/src/java/org/sakaiproject/evaluation/logic/EvalEvaluationSetupServiceImpl.java
> +import freemarker.template.Configuration;
Imports look unused?

2018-04-23 10:02 UTC, RebeccaOxfordUni commented
Have removed the unnecessary imports.

2018-04-23 10:35 UTC, buckett commented
@wl-jenkins test this please

2018-04-23 10:36 UTC, buckett approved these changes

2018-04-23 14:05 UTC, buckett commented
Failing build is related to other issue.

2018-04-23 14:05 UTC, merged