WL-5141: Ability to zip selected files/folders
ox-it/sakai pull request #492
Opened 2018-05-03 10:39 UTC by nicholaswilson100

The functionality this is expected to provide is that a user can navigate around their Resources, select some files and folders and then click 'Zip' which will save a zip file with the same name as their site in their Resources (we're deliberately ignoring the 'exceeding quota' problem and 'downloading the zip file for them' feature for now). Importantly, the zip file should preserve the folder structure of their resources, i.e., if they selected a file inside folder A, then the zip file should have folder A in it and the file inside that.

2018-05-03 10:49 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +import org.sakaiproject.content.util.*;
Sakai prefers expanded imports.

2018-05-03 10:55 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +		Set zipIdSet  = new TreeSet();
Add generics?

2018-05-03 14:12 UTC, nicholaswilson100 commented
ta

2018-05-03 15:17 UTC, buckett requested changes
Really nice feature, I can see that if you're going to stream the file back to the user then it's not worth doing the quota work.

What about dropping the old "Compress to Zip" option on the menu as well (do we need 2 ways of doing it?).

When you're walking a filesystem I would have been tempted to use something more along the style of `java.nio.file.PathMatcher` that holds the sets of files/folders to export and a simpler walker that consults the matcher as it finds files/folders (this is just a comment, this doesn't need fixing).

2018-05-03 15:17 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +			context.put("dropboxMode", Boolean.FALSE);
`dropboxMode` doesn't look to to be used in the template

2018-05-03 15:17 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +		context.put ("resourceProperties", ContentHostingService.newResourceProperties ());
`resourceProperties` doesn't look to be used in the template.

2018-05-03 15:17 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +		context.put("siteTitle", state.getAttribute(STATE_SITE_TITLE));
`siteTitle` doesn't look to be used in the template.

2018-05-03 15:17 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +		String oldCollectionId = (String) state.getAttribute(STATE_COLLECTION_ID);
`oldCollectionId` looks like a copy/paste variable name.

2018-05-03 15:17 UTC, buckett commented on content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
> -			if(caller && caller.checked && caller.checked == true)
Looks to be pure whitespace change.

2018-05-03 15:17 UTC, buckett commented on kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java
> +				else if (isInPath(selectedFiles, selectedFolders, memberId)) {// it's a folder above a selected folder
Comment should be: `it's a folder above a selected folder or file`

2018-05-03 15:17 UTC, buckett commented on content/content-tool/tool/src/webapp/vm/content/sakai_resources_zipFinish.vm
> +		#if ($zipItems.size()>0)
Have a `#else# clause with error, or why bother doing the test as the user will just see an empty page with no cancel button?

2018-05-04 15:43 UTC, nicholaswilson100 commented
Tweaked

2018-05-08 10:52 UTC, buckett approved these changes

2018-05-08 10:52 UTC, buckett commented
Cool, is there a reason for splitting this into two parts?

2018-05-08 12:02 UTC, nicholaswilson100 commented
Only to go by the usual Agile principle 'Iterative, incremental and evolutionary'.  The idea is that you get something small useful and working out fast, show it to the stakeholders and iterate over it to get a better product. That way you maximise the likelihood of giving users what they want. i.e., I don't want to prioritse  improvements to it until the stakeholders have had a chance to use it and input their views.

2018-05-09 08:31 UTC, merged