WL-5143 Fix two assignment pop-up alert issues.
ox-it/sakai pull request #493
Opened 2018-05-03 11:26 UTC by RebeccaOxfordUni

2018-05-03 15:22 UTC, buckett requested changes
Just indentation, otherwise looks fine.

2018-05-03 15:22 UTC, buckett commented on assignment/assignment-tool/tool/src/webapp/js/studentViewSubmission.js
> +        if ($('input[name=new_attachments]').val() === "true" && (inTool === false)) {
The indentation here looks wrong, could you try to match it with the surrounding context, the issue maybe because of differences tabs and spaces.

2018-05-03 15:22 UTC, buckett commented on assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
> +        <input type="hidden" name="new_attachments" value="$!new_attachments" />
The indentation here looks wrong, could you try to match it with the surrounding context, the issue maybe because of differences tabs and spaces.

2018-05-04 08:47 UTC, RebeccaOxfordUni commented
Fixed.

2018-05-04 08:48 UTC, buckett approved these changes

2018-05-04 11:47 UTC, merged