WL-5181 Add common cartridge export facility to resources.
ox-it/sakai pull request #506
Opened 2018-07-17 16:23 UTC by RebeccaOxfordUni

2018-07-18 13:41 UTC, buckett commented
I think it's probably worth formatting the "new" classes here so they are consist. I know they originally came from another project but for source control purposes they are almost new.

2018-07-19 07:49 UTC, RebeccaOxfordUni commented
More formatting done, I had already done quite a lot!

2018-07-19 10:07 UTC, buckett commented
@wl-jenkins test this

2018-07-19 10:08 UTC, buckett commented
@wl-jenkins retest this please

2018-07-19 11:11 UTC, buckett requested changes
Just indentation for now.

2018-07-19 11:11 UTC, buckett commented on master/pom.xml
> +		<dependency>
The indentation here looks wrong, could you try to match it with the surrounding context, the issue maybe because of differences tabs and spaces.

2018-07-19 11:11 UTC, buckett commented on content/content-tool/tool/src/webapp/vm/content/sakai_resources_exportFinish.vm
> +		<h3>
The indentation here looks wrong, could you try to match it with the surrounding context, the issue maybe because of differences tabs and spaces.

2018-07-19 11:11 UTC, buckett commented on content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> +	List<String> selectedFolderIds = new ArrayList<>();
Looks to be just an indentation change here.

2018-07-19 11:11 UTC, buckett commented on common/export-common-cartridge/pom.xml
> +	  <dependency>
The indentation here looks wrong, could you try to match it with the surrounding context, the issue maybe because of differences tabs and spaces.

2018-07-19 13:03 UTC, RebeccaOxfordUni commented
Indentation and spacing fixed.

2018-07-19 13:10 UTC, buckett approved these changes

2018-07-19 13:59 UTC, merged