WL-5213 Modifications to CC export to cope with duplicate filenames,
ox-it/sakai pull request #524
Opened 2018-10-19 16:27 UTC by RebeccaOxfordUni

also modified the links in HTML files so that they work correctly in Canvas.

Note this PR also includes the changes requested in the GitHub comments for WL-5210

2018-10-22 08:42 UTC, buckett requested changes
Nice improvement to the export. Happy to chat about the comments before you wade in.
`linkFixup()` would be nice split up into smaller methods that `linkFixup()` calls, this makes it easier to get an idea of what the method does and makes debugging easier, basically each matcher/replacement section would fit well in a method.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +	public String linkFixup (String content, ContentResource contentResource) {
I think `contentResource` isn't used in this method and can be removed.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +	public String linkFixup (String content, ContentResource contentResource) {
I think `contentResource` isn't used in this method and can be removed.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
>  		String sakaiIdBase = "/group/" + siteId;
I think this can be removed as well as it's not used.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge unsupported encoding exception in linkFixup" + uee);
Much better handling expected exceptions than just catching Exception. The `UnsupportedEncodingException` block could be replaced by `throw new RuntimeException(uee)` as the JDK *has* to support UTF-8 so if that can't be found something serious has gone wrong.

The reason I see for keeping a log block like this is if the character set is pulled form the request or some user input (or is likely to be in the future), but in this case I don't think it's likely.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +		matcher = target.matcher(parsedContent);
I wouldn't re-use `Pattern`/`Matcher` variables between logically different blocks. In refactoring it can result in easy to miss bugs where you're accidentally using a matcher from a previous block.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +						if (link.getKey().indexOf('.') > -1) {
`link.getKey().contains(".")` reads slightly nicer than the `indexOf()`, but if as you're using the position on the next line, I'd just extract a variable `int periodIndex = filename.indexOf('.');` then use it in the test and the `substring`.

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +							filename = link.getKey().substring(0, link.getKey().indexOf('.'));
I think you can just use `filename = filename.substring...`

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge unsupported encoding exception in linkFixup" + uee);
Just re-throw as a `RuntimeException`

2018-10-22 08:42 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +				log.error("export-common-cartridge unsupported encoding exception in linkFixup" + uee);
Indentation and rethrow as `RuntimeException`.

2018-10-23 14:59 UTC, RebeccaOxfordUni commented
All changes requested done.

2018-10-23 15:21 UTC, buckett approved these changes

2018-10-30 09:50 UTC, merged