WL-5234 Add assignments to site export code and improve structure.
ox-it/sakai pull request #543
Opened 2018-12-21 17:29 UTC by RebeccaOxfordUni

2018-12-21 17:41 UTC, buckett commented
Build looks to have failed for this.

2019-01-09 12:11 UTC, buckett requested changes
Although lots of comments most are small things I think.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			zipEntry = new ZipEntry("cc-objects/export-errors");
Why is this commented out rather than removed?

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			String errId = exportUtil.getResourceId();
Why is this commented out rathter than removed?

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			out.println("      <file href=\"course_settings/module_meta.xml\"/>");
Why is this commented out rather than removed?

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +			String URL = null;
All caps is normally used for static constants, should be `url` instead.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +					if (sakaiId.startsWith("/content/"))
This looks very similar to the chunk from 157 onwards. Should it be duplicated?

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +		return assignmentsExport.getAssignmentsInSite(siteId);
Indentation is off.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge type error outputting assignments" + te);
I'd switch the `+` to a `,` so we get a stack trace here in the logs.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge permission error outputting assignments" + pe);
I'd switch the `+` to a `,` so we get a stack trace here in the logs.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge ID unuse error outputting assignments" + ide);
I'd switch the `+` to a `,` so we get a stack trace here in the logs.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge server overload error outputting assignments" + soe);
I'd switch the `+` to a `,` so we get a stack trace here in the logs.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean forpoints = false;
I would expect this to be CamelCase, so `forPoints`.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private double maxpoints = 0.0;
Should be CamelCase, so `maxPaints`.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean allowtext;
Should be CamelCase so `allowText`

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean allowfile;
Should be CamelCase so `allowFile`

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private double maxpoints = 0.0;
Default value is redundant and other fields `AssignmentResource`/`Resource` aren't initialised.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean gradable = false;
Default value is redundant and other fields `AssignmentResource`/`Resource` aren't initialised.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean forpoints = false;
Default value is redundant and other fields `AssignmentResource`/`Resource` aren't initialised.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				res.setAllowtext(false);
Aren't these redundant as that will be the default value?

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				switch (typeOfSubmission) {
I'd find it easier to read this block if it was:
```
res.setAllowtest(typeOfSubmission == 1 || typeOfSubmission == 3);
res.setAllowFile(typeOfSubmission == 2 || typeOfSubmission == 3);
```
That way it's clear both are set.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +	public AssignmentsExport(ExportUtil exportUtil) {
I would pass in the AssignmentService in the constructor and that way you don't depend on the cover and the class could have some tests.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +		Iterator assignmentIterator = AssignmentService.getAssignmentsForContext(siteId);
Can add type to the Iterator to avoid the later cast.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				res.setIslink(false);
Redundant as it's the default value.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				res.setIsbank(false);
Redundant as it's the default value.

2019-01-09 12:11 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +					assignmentId = assignmentId.substring(assignmentId.indexOf("/") + 1);
Why not just call `assignment.getId()`? Is it the case where the attachments may be for a different assignment?

2019-01-10 11:12 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			zipEntry = new ZipEntry("cc-objects/export-errors");
Removed as nothing is written to the error file at the moment.

2019-01-10 11:12 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			String errId = exportUtil.getResourceId();
Removed as nothing is written to the error file at the moment.

2019-01-10 11:12 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			out.println("      <file href=\"course_settings/module_meta.xml\"/>");
No module is created so removed.

2019-01-10 11:13 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +			String URL = null;
Changed.

2019-01-10 11:13 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +					if (sakaiId.startsWith("/content/"))
They add different bits to the CC so have left these as they are.

2019-01-10 11:49 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +	public AssignmentsExport(ExportUtil exportUtil) {
Changed.

2019-01-10 11:49 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +		Iterator assignmentIterator = AssignmentService.getAssignmentsForContext(siteId);
Ok.

2019-01-10 11:49 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				res.setIslink(false);
Changed.

2019-01-10 11:49 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				res.setIsbank(false);
Changed.

2019-01-10 12:22 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +					assignmentId = assignmentId.substring(assignmentId.indexOf("/") + 1);
Changed.

2019-01-10 12:31 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean gradable = false;
Removed.

2019-01-10 12:35 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean forpoints = false;
Changed.

2019-01-10 12:35 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean forpoints = false;
Removed.

2019-01-10 12:35 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private double maxpoints = 0.0;
Changed.

2019-01-10 12:35 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private double maxpoints = 0.0;
Changed.

2019-01-10 12:35 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean allowtext;
Changed.

2019-01-10 12:35 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentResource.java
> +	private boolean allowfile;
Changed.

2019-01-10 12:36 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				res.setAllowtext(false);
Changed.

2019-01-10 12:42 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/AssignmentsExport.java
> +				switch (typeOfSubmission) {
Change made, this wasn't my code originally.

2019-01-10 13:02 UTC, RebeccaOxfordUni commented
I think I've made all the requested changes Matthew.

2019-01-10 13:35 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			out.println("      <file href=\"course_settings/module_meta.xml\"/>");
This looks to still be in there.

2019-01-10 16:39 UTC, buckett commented
I think there are a few missed, ones inside CCExport that are marked as Outdated, but still apply. I'll comment on one.

2019-01-10 16:40 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge server overload error outputting assignments" + soe);
I think this still isn't fixed.

2019-01-11 12:08 UTC, buckett commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +			log.error("export-common-cartridge server overload error outputting assignments" + soe);
These still are there I think, although line numbers have shifted about.

2019-01-11 16:39 UTC, RebeccaOxfordUni commented on common/export-common-cartridge-util/src/java/org/sakaiproject/exporter/util/CCExport.java
> +//			out.println("      <file href=\"course_settings/module_meta.xml\"/>");
Should be gone now.

2019-01-14 08:53 UTC, buckett approved these changes

2019-01-14 08:53 UTC, merged